### ISSUE TITLE
delivery.some is not a function

### ISSUE THREAD

**Issue by iml885203** [next-theme/hexo-optimize#23]
I got this error when upgrading hexo-optimize to ^3.2.0.

- hexo: ^6.3.0
- next: ^8.13.1

```
TypeError: delivery.some is not a function
    at /Users/logan/Logan/blog-source/node_modules/hexo-optimize/lib/filter.js:29:18
    at String.replace (<anonymous>)
    at minify (/Users/logan/Logan/blog-source/node_modules/hexo-optimize/lib/filter.js:11:13)
    at /Users/logan/Logan/blog-source/node_modules/hexo-optimize/lib/filter.js:103:11
error Command failed with exit code 2.
```

config:
```
filter_optimize:
  enable: true
  # static resource versioning
  versioning: false
  css:
    # minify all css files
    minify: true
    # bundle loaded css files into one
    bundle: false
    # use a script block to load css elements dynamically
    delivery: false
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
      # support full path only
      - css/main.css
    excludes:
  js:
    # minify all js files
    minify: true
    # bundle loaded js files into one
    bundle: true
    excludes:
    # remove the comments in each of the js files
    remove_comments: false
  html:
    # minify all html files
    minify: true
    excludes:
  # set the priority of this plugin,
  # lower means it will be executed first, default of Hexo is 10
  priority: 12
```
