### ISSUE TITLE
missing `</html></body><head>` tag

### ISSUE THREAD

**Issue by uiolee** [next-theme/hexo-optimize#31]
hi there.
I install `hexo-optimize`, and run `hexo g`.
Then I found that 

- the html file missed `<html></html></body><head></head>` tag.
- `<!DOCTYPE html>` became `<!doctypehtml>`

may I ask if this is normal?

**Comment by stevenjoezhang** [comment]
HTML minify is enabled by default. You can disable it by setting
```yml
filter_optimize:
  html:
    # minify all html files
    minify: false
```

in Hexo `_config.yml`
